SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [tSQLt].[Private_ExpectException] (
		[i]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [tSQLt].[Private_ExpectException] SET (LOCK_ESCALATION = TABLE)
GO
